' <summary>example file demonstrating interfaces and classes</summary>
' <remarks>detailed file description comes here<BR><BR>
' The original unfiltered source of this file : <A HREF="http://trac.sevo.org/projects/doxyvb/browser/trunk/samples/class_with_interface.vb">class_with_interface.vb</A></remarks>
' \mainpage Example for the Doxygen VB .NET filter
' \section intro_sec Introduction
'
' This is a sample documentation generated by Doxygen 1.6.3<BR>
' with applied patches from <A HREF="http://trac.sevo.org/projects/doxyvb/wiki/WikiStart/Preparing">http://trac.sevo.org/projects/doxyvb/wiki/WikiStart/Preparing</A><BR>
' (See also the <A HREF="https://bugzilla.gnome.org/show_bug.cgi?id=619728">Doxygen Bug 619728</A>)
'
' The Doxyfile used to generate this documentation and the documented sample sources can be found here: 
' <A HREF="http://trac.sevo.org/projects/doxyvb/browser/trunk/samples/">http://trac.sevo.org/projects/doxyvb/browser/trunk/samples/</A>
'
' \section install_sec Installation
'
' \subsection step1 Step 1: Opening the box

Imports System.IO
Imports System.Threading
Imports System.Runtime.Serialization

''' <summary>
''' simple enumeration
''' </summary>
''' <remarks>description of the simple enumeration</remarks>
Public Enum SampleEnum As Short
    Value1         ' first value
    Value2         ' second value
    Value3 = 1234  ' third assigned value
    Value4         ' fourth value
End Enum

''' <summary>
''' sample interface
''' </summary>
''' <remarks>interface inherits IDisposable</remarks>
Public Interface ISample
    Inherits IDisposable

    ''' <summary>
    ''' simple property
    ''' </summary>
    ''' <value>returns a string value</value>
    Property StringProperty() As String

    ''' <summary>
    ''' read only property
    ''' </summary>
    ''' <value>returns an Integer value</value>
    ReadOnly Property IntegerProperty() As Integer

    ''' <summary>
    ''' simple method
    ''' </summary>
    ''' <remarks>no remarks</remarks>
    Sub SampleMethod()

    ''' <summary>
    ''' simple method with parameters
    ''' </summary>
    ''' <param name="pFirst">first parameter is a String</param>
    ''' <param name="pPointer">second parameter is a pointer to an Integer</param>
    ''' <remarks></remarks>
    Sub SampleMethodWithParams(ByVal pFirst As String, ByRef pPointer As Integer)

    ''' <summary>
    ''' simple function with a parameter
    ''' </summary>
    ''' <param name="pFirst">Double parameter</param>
    ''' <returns>a Double value</returns>
    ''' <remarks></remarks>
    Function SampleFunction(ByVal pFirst As Double) As Double

    ''' <summary>
    ''' simple event with a parameter
    ''' </summary>
    ''' <param name="Sender">event sender object</param>
    Event OnSomeEvent(ByVal Sender As Object)

End Interface

''' <summary>
''' simple class implementing an interface
''' </summary>
''' <remarks>implements ISample</remarks>
Public Class SampleClass
    Implements ISample

    Private someInteger As Integer ' simple private integer value
    Public someString As String    ' simple public string value

    ''' <summary>
    ''' simple property
    ''' </summary>
    ''' <value>some string</value>
    ''' <returns>some string</returns>
    ''' <remarks>implements ISample.IntegerProperty</remarks>
    Public Property StringProperty() As String Implements ISample.StringProperty
        Get
            Return someString
        End Get
        Set(ByVal value As String)
            someString = value
        End Set
    End Property

    ''' <summary>
    ''' readonly property
    ''' </summary>
    ''' <value>integer value</value>
    ''' <returns>same interger value</returns>
    ''' <remarks>implements <see cref="ISample.IntegerProperty">IntegerProperty</see></remarks>
    Public ReadOnly Property IntegerProperty() As Integer Implements ISample.IntegerProperty
        Get
            Return someInteger
        End Get
    End Property

    ''' <summary>
    ''' function with parameter
    ''' </summary>
    ''' <param name="pFirst">simple parameter</param>
    ''' <returns>some double value</returns>
    ''' <remarks></remarks>
    Public Function SampleFunction(ByVal pFirst As Double) As Double Implements ISample.SampleFunction

    End Function

    ''' <summary>
    ''' simple method
    ''' </summary>
    ''' <remarks></remarks>
    Public Sub SampleMethod() Implements ISample.SampleMethod

    End Sub

    ''' <summary>
    ''' method with parameters
    ''' </summary>
    ''' <param name="pFirst">simple param</param>
    ''' <param name="pPointer">pinter</param>
    ''' <remarks></remarks>
    Public Sub SampleMethodWithParams(ByVal pFirst As String, ByRef pPointer As Integer) Implements ISample.SampleMethodWithParams

    End Sub

    ''' <summary>
    ''' some event
    ''' </summary>
    ''' <param name="Sender">sender of object type</param>
    ''' <remarks></remarks>
    Public Event OnSomeEvent(ByVal Sender As Object) Implements ISample.OnSomeEvent

    Private disposedValue As Boolean = False        ' generated by VS class designer

    ''' <summary>
    ''' IDisposable implementation
    ''' </summary>
    ''' <param name="disposing"></param>
    ''' <remarks></remarks>
    Protected Overridable Sub Dispose(ByVal disposing As Boolean)
        If Not Me.disposedValue Then
            If disposing Then
            End If

        End If
        Me.disposedValue = True
    End Sub

    ''' <summary>
    ''' IDisposable implementation
    ''' </summary>
    ''' <remarks></remarks>
    Public Sub Dispose() Implements IDisposable.Dispose
        Dispose(True)
        GC.SuppressFinalize(Me)
    End Sub

End Class
