' <summary>contains only a header describing the project</summary>
' \mainpage Example for the Doxygen VB .NET filter
' \section intro_sec Introduction
'
' This is a sample documentation generated by <A HREF="http://www.stack.nl/~dimitri/doxygen/changelog.html">Doxygen 1.7.0</A> and <A HREF="http://trac.sevo.org/projects/doxyvb/">VB .NET filter</A><BR>
'
' VB .NET filter is a awk script by Vsevolod Kukol, which adds VB.NET support to <A HREF="http://www.stack.nl/~dimitri/doxygen/index.html">Doxygen</A>.<BR>
' Project page: <A HREF="http://trac.sevo.org/projects/doxyvb/">http://trac.sevo.org/projects/doxyvb/</A>
'
' The Doxyfile used to generate this documentation and the documented exsample sources can be found here: <BR>
' <A HREF="http://trac.sevo.org/projects/doxyvb/browser/trunk/samples/">http://trac.sevo.org/projects/doxyvb/browser/trunk/samples/</A>
'
' \dir samples contains example files demostrating Doxygen VB.NET filer functionality
' \package samples <summary>contains example classes demostrating Doxygen VB.NET filter functionality</summary>

