' <summary>contains only a header describing the project</summary>
' \details The original unfiltered source of this file: <A HREF="http://trac.sevo.org/projects/doxyvb/browser/trunk/samples/dirinfo.vb">dirinfo.vb</A>
' \mainpage Example for the Doxygen VB 6/.NET filter
' \section intro_sec Introduction
'
' This is a sample documentation generated by <A HREF="http://www.stack.nl/~dimitri/doxygen/changelog.html">Doxygen 1.7.0</A> with the <A HREF="http://trac.sevo.org/projects/doxyvb/">VB filter</A> by Vsevolod Kukol.<BR>
'
' The VB filter is an awk script, which adds VB6 and VB.NET support to <A HREF="http://www.stack.nl/~dimitri/doxygen/index.html">Doxygen</A>.<BR><BR>
' Project page: <A HREF="http://trac.sevo.org/projects/doxyvb/">http://trac.sevo.org/projects/doxyvb/</A>
'
' The Doxyfile used to generate this documentation and the documented exsample sources can be found here: <BR>
' <A HREF="http://trac.sevo.org/projects/doxyvb/browser/trunk/samples/">http://trac.sevo.org/projects/doxyvb/browser/trunk/samples/</A>
'
' \author Vsevolod Kukol
' \version 2.4.0
' \date    09.10.2011
'
' \dir samples contains example files demostrating the Doxygen VB filter functionality
' \package DotNET <summary>contains example classes demostrating VB.NET filter functionality</summary>
' \package ClassicVB <summary>contains example classes demostrating VB6 filter functionality</summary>

